### ISSUE TITLE
我有个想法是在最高利润右侧再扩一列【最高合计一单利润】

### ISSUE THREAD

**Issue by SilyASilyF** [NathanKun/resonance-columba#10]
这样直接跳过计算，得到A点的货物卖到BCDE哪个城，一张订货单的总利润最高。
这是在不考虑疲劳的情况下，考虑最高性价比的订单。

更进一步的话，还可以去计算最高合计一单利润/合计容量，得到同样条件下效率最高的订单。

再进一步还可以计算最高合计一单利润/合计容量/路程疲劳，得到考虑疲劳的情况下最高效率的订单。

刚才打完字突然意识到好像这个内容已经包含在了前面老哥说的路线规划里，不过既然已经写好了，发出来仅供参考。

PS：最后我又意识到好像这个利润从EXCEL建表最开始就会受到角色生活技能的极大影响，比如斧王好像可以直接提高矿场30%出货量，又比如朱利安提高7港20%出货和44%出虾量，我觉得可以把这个也考虑进去，在后期更新为一个可以按角色最大生活技能计算的路线规划系统。

**Comment by SilyASilyF** [comment]
目前好像棉花的Q群里的机器人已经实现这个功能的查询了，或许可以close掉？不过毕竟Q群人数有限……
或许可以考虑直接在表格上方的搜索栏那一行做一个下拉框？效果类似机器人提供的效果：
75000 自 荒园站 去往 7号自由港
71000 自 XXX 去往 XXX
68000 自 XXX 去往 XXX

这样

**Comment by NathanKun** [comment]
#45 的新路线模拟页面提供这个功能了。
