### ISSUE TITLE
为什么是“希望最多进货次数”？

### ISSUE THREAD

**Issue by puresox** [NathanKun/resonance-columba#102]
请问一图流中为什么是“希望最多进货次数”，而不是“进货次数”，我发现一图流中不同的线路用的进货次数是不一样的，比如我设置4，有的线路经过次数就是4，有的是3，有的是2，如果进货次数不同的话，对利润进行比较就没有意义啊。

**Comment by NathanKun** [comment]
强行统一进货次数的话大部分路线都会出现浪费低价货物的情况，使得无法充分利用每一本进货书。
但我确实有打算做这个选项给不介意浪费进货书的人使用。

**Comment by puresox** [comment]
请问低价货物是怎么定义的啊，是利润低还是成本低啊，而且一图流是会给利润进行排序的，有的时候某一条线路如果用四本进货书的话利润为90w（56疲劳），但是它只显示2本书的利润56w，导致第一名是另一条线路，4本书80w（56疲劳），你看，同样是四本书，同样的疲劳，“浪费低价货物”的反而获利得更多，这不合理吧。

**Comment by NathanKun** [comment]
低价货物指利润低货物，是我没说清楚。
对任意一条线路你用的书越多利润自然是越高的。
但一图流对书的使用是以不浪费为目标。
假设你设置了最高用5书，一通计算下来，如果买利润为前2的商品，需要进7次货才能满仓，所以否决。
如果买利润前3的商品，只需要进货3次就能满仓，所以推荐。
这时候作为玩家如果你强行用5书，你当然可以买更多的高利润货物，但是利润排名第三的货物你肯定是无法全买了，只能买一部分，这就叫做浪费了低利润货物，你没有充分利用到每一本进货书。
希望以上例子能帮助你理解一图流现在的算法。

**Comment by puresox** [comment]
了解了，感谢🙏！希望出一个“不介意浪费进货书”的功能，倒不是我想浪费进货书，我只是想看看，相同进货书的情况下，哪条线路利润/单位疲劳利润高。

**Comment by Yanzzl** [comment]
请问以后这个功能会出每个来回的“希望最多进货次数”吗？ 比如有时去程4书，返程2书是最优解。现在的逻辑如果想限定来回6本书，就只能选择“希望最多进货次数”为3，然后出现的组合有(3,3) (3,2)等，这样无法同数量进货书对比。我也是刚玩不久，也可能实际游戏中不存在我说的这种状况。。。

**Comment by NathanKun** [comment]
@Yanzzl 这个功能理论上是能做的，但一图流的界面我想尽量简单明了，不想添加太多的控件。
需求我先记着，之后我看看怎么做吧。
