### ISSUE TITLE
18号更新后布局变了

### ISSUE THREAD

**Issue by sarauuoi** [NathanKun/resonance-columba#105]
![image](https://github.com/NathanKun/resonance-columba/assets/17095989/79918a9d-3fef-409e-a85d-850d1145f780)
也不知道什么情况..用的chrome,不知道是不是我的问题..用edge跟手机均正常

**Comment by NathanKun** [comment]
清除浏览器缓存试试？
CTRL+F5

**Comment by sarauuoi** [comment]
不行😂,cookie也清过几次了.实在不行我用别的浏览器看吧
