### ISSUE TITLE
一图流中的购买逻辑有问题

### ISSUE THREAD

**Issue by puresox** [NathanKun/resonance-columba#113]
![IMG_20240322_123157](https://github.com/NathanKun/resonance-columba/assets/17718921/6c84aad6-a995-46bb-b4b3-61231689fb4b)
![IMG_20240322_123120](https://github.com/NathanKun/resonance-columba/assets/17718921/134a0d1b-75b0-425f-9639-52a2e15213cc)
如图，修城-7港路线发动机是亏本的，却让我买发动机。
正确的购买逻辑应该是按照单件利润由高到低的顺序依次购买，直到货仓满；即使货仓不满也不会买税后亏本的商品。

**Comment by EEEExciting** [comment]
下面图里的计算是不包含议价设置的，所以你看着亏，但是把议价利润算进来就比别的商品都高了

**Comment by NathanKun** [comment]
数据页面只是价位的简单减算。
一图流计算包含抬砍价，抬砍后不亏了就会买。
亏钱的商品不会买的。

购买逻辑也正是你说的按照单件利润由高到低的顺序依次购买。

**Comment by puresox** [comment]
明白了，感谢！
