### ISSUE TITLE
关于一图流算法问题

### ISSUE THREAD

**Issue by EEEExciting** [NathanKun/resonance-columba#114]
例如下图
![image](https://github.com/NathanKun/resonance-columba/assets/23447813/a09be3bd-ffdf-4e19-b853-c86a612737f1)
修格里->研究所和矿场->研究所两条路线
当供货书数量为4时，无论利润还是单位疲劳利润，矿场出发都是优于其他路线的，玩家也大概率会选择这条路线
![image](https://github.com/NathanKun/resonance-columba/assets/23447813/eb6655f9-ec39-476d-8bc2-c72bb84e9f45)
但如果对比3书数据可知，在4书情况下修城路线选用的仍然是3书方案
![image](https://github.com/NathanKun/resonance-columba/assets/23447813/e27ee943-1bda-4c33-bb3b-f79573c78289)
通过模拟计算（我的仓位为650），实际4书时修城出发购买方案应为
红茶单次73个，650/73=8.9>5，红茶=73x5=365，剩余仓位650-365=285，总利润49932x5=249660
烤鸡单次90个，285/90=3.1<5，烤鸡=285，利润（663-335）x285=93480，总利润343140，单位疲劳利润11069
对比同样4书矿场路线总利润376715，单位疲劳利润9659，修城路线单位疲劳利润最高，总利润第二，在某些行情下利润也会是新算法更高，那么此时玩家跑当前算法下的最优路线反而会造成利润/疲劳/供货书的损失
目前算法是计算“将单个商品利润排序后，我想购买到前X种商品需要的最小供货书数量”，算法更关注商品品类的数量
但在实际使用中，玩家更关注利润/单位疲劳利润/购买商品总量（是否满仓）
对于具体买了3种商品还是4种商品其实并不关心，在逻辑上商品品类的数量也与利润没有必然联系
所以麻烦作者考虑下目前算法与实际应用需求是否存在不匹配的情况

PS：我在商会讨论区也发布了一个类似问题，但没有具体案例导致描述的不够清晰，而且感觉你讨论区看的也比较少，所以在这里重新发了一下

**Comment by NathanKun** [comment]
补充解释一下：“买了3种商品还是4种商品”本质上是算法要求一定要买完进了的货。

**Comment by NathanKun** [comment]
个人来说，我实际操作时更看重不浪费进货书，用更低利润的商品来满仓，而不是再进一次货用高利润商品来满仓。所以算法上我也是这么写的。

因为无脑再进一次货来满仓的话可能会导致进的货只能买一点点，这时候就很亏，算法上可能需要设置一个允许浪费的阈值，而这个阈值又不一定每个人都同意，到时候又会有人来问我“为什么我按着一图流用的进货书，最后剩下来那么多货买不走”，我又得头疼😄。

**Comment by EEEExciting** [comment]
现有算法其实是表达在某一条路线中，如何让供货书利润最大化，在这个算法中路线是已经选定好的
而实际应用场景中要先“选”出一条路线，但目前算法在比较的时候，没有进行变量控制，导致展现结果出现差异
由于受限于当前行情，我在案例只表现出了单位疲劳利润排名的提高，在实际使用中我也遇到过新算法总利润高于现有算法的案例，相同供货书数量的情况下总利润提高自然也代表了单位进货书利润的提高，所以新算法并不一定会导致进货书利润会下降
如有需要，我后续可以在遇到这种行情的时候在这里继续补上截图

**Comment by EEEExciting** [comment]
只考虑不浪费进货书而填满仓位，这个思路和游戏需求其实不太匹配吧
要是只填仓位，很多城市其实都不会超过1本书，因为有很多超低价商品可以买比如土豆沙子之类的，只是商会没录入而已，毕竟大家都知道这部分商品提供的利润极低
换句话说，只要用了供货书，店里一定会留下货物

**Comment by EEEExciting** [comment]
留下货物其实就是某种程度的“浪费了供货书”
从游戏设计角度讲，其实供货书的作用就是提高单次交易商品数量，进而提高利润，而交易必然需要疲劳消耗，所以供货书对应的作用就是提高利润/单位疲劳利润的
而减少供货书的使用实际就是买入更多低利润商品来填充仓位，相当于用利润/单位疲劳利润换书
那么玩家选取供货书数量的过程，其实就是把握这个双向交换平衡的过程
换个角度讲，我认为目前算法在某些情况下没有表现出这个双向交换的具体数据，比如案例中的“4本书”的场景

**Comment by NathanKun** [comment]
相同进货书数量下，最优解是一定的，就是按商品利润排名，从上往下买。
不存在新算法比这个利润更高，除非新算法允许浪费部分利润较低的货物进货了但是不买走。

另外，“要是只填仓位，很多城市其实都不会超过1本书”是不对的，首先不能买亏本商品。
其次，随着玩家允许用的进货书数量上升，算法会排除利润最低的商品。
所以不是“考虑不浪费进货书而填满仓位”，而是在玩家能接受的进货书数量上限下，给出不浪费进货书而填满仓位的最优购买方式。

**Comment by NathanKun** [comment]
> 留下货物其实就是某种程度的“浪费了供货书” 从游戏设计角度讲，其实供货书的作用就是提高单次交易商品数量，进而提高利润，而交易必然需要疲劳消耗，所以供货书对应的作用就是提高利润/单位疲劳利润的 而减少供货书的使用实际就是买入更多低利润商品来填充仓位，相当于用利润/单位疲劳利润换书 那么玩家选取供货书数量的过程，其实就是把握这个双向交换平衡的过程 换个角度讲，我认为目前算法在某些情况下没有表现出这个双向交换的具体数据，比如案例中的“4本书”的场景

正如我第一条评论所说，我能想到的方法就是增加一个“允许浪费部分低价商品”的选项了。

**Comment by EEEExciting** [comment]
![image](https://github.com/NathanKun/resonance-columba/assets/23447813/a9796432-736c-41c4-bd1d-ee699d4f8142)
![image](https://github.com/NathanKun/resonance-columba/assets/23447813/e41c5f39-75bb-4237-a640-560f86df1bf7)
![image](https://github.com/NathanKun/resonance-columba/assets/23447813/e4f663d7-8352-4b32-8f7d-d63c9b6a6859)
我抓到数据了，可以看下这里修城到研究所和工厂的数据，选定3书，工厂利润优于研究所，但研究所用的2书数据，如果研究所强制使用3书，数据必然优于工厂，我先把图贴出来，下边补计算过程

**Comment by NathanKun** [comment]
书多=利润多没毛病
但是为什么一图留让你用2书而不是3书，因为3书进的烤鸡买不完，所以第三本书没有充分利用，所以不建议。

**Comment by EEEExciting** [comment]
仓位650，3书修->研究所
红茶73*4=292，剩余仓位358，利润178996
烤鸡90*4=358，剩余仓位0，利润117066，总利润296062
但是目前算法却是修->工厂的利润245758路线优于修->研究所
相同供货书利润却更低了，和算法设计初衷相悖

**Comment by NathanKun** [comment]
因为烤鸡90x4=360 > 剩余仓位358
剩下两只烤鸡只能留给老板了，所以不推荐。
很好的极端例子，确实展示出了现有算法的最差推荐。

那么我们现在假设，烤鸡一次能进143只。

仓位650，3书修->研究所
红茶73x3=219，剩余仓位431，利润134247
烤鸡143x3=429，剩余仓位2，利润140283
总利润274530，单位书利润91510

仓位650，4书修->研究所
红茶73x4=292，剩余仓位358，利润178996
烤鸡358，利润117066
总利润296062，单位书利润74015

这时按你的算法单位书利润降低了20%，因为浪费了143x4-358=214只烤鸡。

**Comment by EEEExciting** [comment]
> 因为烤鸡90x4=360 > 剩余仓位358 剩下两只烤鸡只能留给老板了，所以不推荐。 很好的极端例子，确实展示出了现有算法的最差推荐。
> 
> 那么我们现在假设，烤鸡一次能进143只。
> 
> 仓位650，3书修->研究所 红茶73x3=219，剩余仓位431，利润134247 烤鸡143x3=429，剩余仓位2，利润140283 总利润274530，单位书利润91510
> 
> 仓位650，4书修->研究所 红茶73x4=292，剩余仓位358，利润178996 烤鸡358，利润117066 总利润296062，单位书利润74015
> 
> 这时按你的算法单位书利润降低了20%，因为浪费了143x4-358=214只烤鸡。

可是实际应用场景是：
在选定供货书数量的前提下，多路线进行利润比较
而不是
先选定一条路线，再在不同供货书数量之间进行利润比较

**Comment by NathanKun** [comment]
懂你意思了，问题本质在数据不能横向比较，而不是应不应该多用那一本书。
这样的话甚至都不需要增加选项了，不能横向比较的话这个图确实会给出错误信息。
我改一下算法直接无脑玩家给多少书就用多少书得了。

**Comment by NathanKun** [comment]
感谢你的提醒以及详细的解释。

**Comment by EEEExciting** [comment]
> 懂你意思了，问题本质在数据不能横向比较，而不是应不应该多用那一本书。 这样的话甚至都不需要增加选项了，不能横向比较的话这个图确实会给出错误信息。 我改一下算法直接无脑玩家给多少书就用多少书得了。

对的，其实我最开始想表达的就是当前算法与玩家使用时需求不匹配，并非算法本身有问题，是我没表达清楚
另外由于现在还有利用商品高净值通过议价提利润的跑商方法，代表地就是工厂
所以我建议能否可以来回路线分别设置书和溢价
比如修->工厂，单纯因为活动红茶利润超高，所以单次跑商利润高但净值低，砍价抬价收益不大，这时候不需要议价
但工厂->修的返程路线商品虽然利润低甚至负利润，但净值很高，通过议价可以获取很高收益，这时候又需要议价
另外有些单程路线利润很高，返程甚至空跑都可以获得不错的整体收益，这时候也需要单独设置书和砍/抬价

**Comment by EEEExciting** [comment]
> 感谢你的提醒以及详细的解释。

更应该感谢你！没商会都不知道怎么玩这个游戏了

**Comment by Yanzzl** [comment]
赞一个，前天就发现没法进行来回同书的利润比较，以为是我玩的不久游戏理解问题。今天看你们讨论才明白问题在哪。

**Comment by EEEExciting** [comment]
另外我最近打算做一个用商会规划跑商路线的教程，视频会发在B站
想把你的GitHub项目信息和B站信息放在视频里表达感谢
请问一下作者有B站ID吗？

**Comment by NathanKun** [comment]
好的，我这两天尽快改一下一图流算法。
我b站名 Thunder shadow，uid 65483。

**Comment by NathanKun** [comment]
新算法已更新。

**Comment by NathanKun** [comment]
@all-contributors please add @EEEExciting for ideas
