### ISSUE TITLE
一图流&硬核模拟卖出计税错误

### ISSUE THREAD

**Issue by EEEExciting** [NathanKun/resonance-columba#133]
![image](https://github.com/NathanKun/resonance-columba/assets/23447813/1cac6d69-c579-4d7f-85ef-453d7357abb2)
弹丸装置显示成本2332
![image](https://github.com/NathanKun/resonance-columba/assets/23447813/6f3dfb0b-a745-4310-8079-59ba10acbd79)
实际游戏内购买含税成本2332，与模拟一致，价格浮动102%
![image](https://github.com/NathanKun/resonance-columba/assets/23447813/f10059cd-e74c-4570-90dc-6d1d64db6907)
游戏内售价标价2335，与模拟一致，价格浮动98%
![image](https://github.com/NathanKun/resonance-columba/assets/23447813/8f329a4d-d2ca-4846-89b2-545770c5e7f7)
游戏内含税售价约2330.64，低于模拟，税额2335*90-209758=392
![image](https://github.com/NathanKun/resonance-columba/assets/23447813/a4086526-da67-4e5c-bd11-0298ffe87177)
产地价格浮动102%，出售地价格浮动98%，与“数据”界面数据相符，确认不存在由于商会数据延迟产生的误差
含税成本共计209880，税后收入共计209758，扣完税实际是亏损的，商会由于售出未计税显示盈利，但还是游戏里的利润更离谱

附税额计算方法：
(未计税售价-未计税成本)*税率*商品数量
即：(2335-2190)*3%*90=391.5，取整392(不确定是四舍五入还是上取整，大概是上取整)，与游戏内数据相符

**Comment by NathanKun** [comment]
怪了，税是肯定有算的，当时计算做完后我还检查过和游戏里是对的上的。不知道是游戏算法改了还是我一开始就没做对，我一会儿检查检查。

**Comment by NathanKun** [comment]
嗯研究出来了，是我的税率算法有问题。

我的算法时 （卖出价-含税买入价）* 卖出地税率
实际应该是 （卖出价-税前买入价）* 卖出地税率
含税买入价 比 税前买入价 要高，导致 卖出地税率 下降，就出现了你例子中的明明是亏钱，模拟结果确是不亏的情况。

修改后和你给的数据一致了。
<img width="776" alt="image" src="https://github.com/NathanKun/resonance-columba/assets/15254235/d1e57399-236b-47a6-808d-357b2e171590">

感谢你的提醒和非常详细的例子。

**Comment by NathanKun** [comment]
https://github.com/all-contributors please add @EEEExciting for bug

**Comment by NathanKun** [comment]
@all-contributors please add @EEEExciting for bug
