### ISSUE TITLE
关于一图流的算法问题

### ISSUE THREAD

**Issue by jiluowuyan** [NathanKun/resonance-columba#141]
刚刚拉货的时候发现的.我拉过去的发财树是负收益,然后我查了一下数据
![Snipaste_2024-03-27_09-17-38](https://github.com/NathanKun/resonance-columba/assets/49177073/8d08b80d-9cdd-4fd5-8ff0-3ce150666494)
但是在一图流里,点开运货详情依旧把负收益的货物算了进去,可以筛选掉吗?
![Snipaste_2024-03-27_09-17-57](https://github.com/NathanKun/resonance-columba/assets/49177073/5f23fc6a-307d-4b0f-9fea-e52c4dedd5f5)

**Comment by NathanKun** [comment]
数据页面的计算不包含个性化设置，所以数据里显示负收益但一图流算出来不一定会亏。

一图流里不会推荐亏钱商品，比如极端情况下你会发现铁盟修成路线无推荐 。

如果你按照一图流买了货，卖的时候发现亏钱了，那可能是价格变动了，或者个性化设置与实际不符，又或者是实际买卖操作的时候抬砍和输入的不一样。

**Comment by jiluowuyan** [comment]
ok, 理解意思了, 非常感谢回复!
