### ISSUE TITLE
怎么稳定获取商品实时价格

### ISSUE THREAD

**Issue by tjulhx** [NathanKun/resonance-columba#16]
1.由PC端的多开模拟器通过本地服务操作模拟器，获取商品实时价格，做图像处理，上传到数据库内
2.平台提供登录功能，赋予编辑管理权限。（最简单
3.对当前正在使用的商品实时表增加一个版本，类似GitHub的commit，提供一个专门用来记录修改的数据表，字段类似如下：
修改时间，商品名称，商品趋势，商品价格，所属城市，commit版本号
定期检查是否有当前版本号的修改记录，大约5分钟跑一次，根据记录数据改商品实时表同时更新commit。
可能想的过于理想化了，也可能想的太复杂了，up主自己再看看

**Comment by puresox** [comment]
不需要图像处理，抓包能直接抓到全游戏所有商品在当前站点的价格

**Comment by tjulhx** [comment]
抓包方案是稳定就是有点麻烦，需要9个账号，成本优点高。

**Comment by puresox** [comment]
你要这样想，只要你开九个小号，你就可以成为全游戏实时性最高（数据更新间隔仅仅是登录游戏的时间）的价格数据分享站，全游戏的玩家都要依赖你，这么一想是不是觉得很值

**Comment by tjulhx** [comment]
哈哈，你这典型的投资家风格啊
excel表格那个里面有三个优点：在线聊天、问题讨论、实时报价
你说的实时性没毛病，但是黑子不是黑black统计的至少十分钟内做交易，价格不会有变化，它跟股票不一样
如果说，我上面三个功能我都有，那么可不可以在实时性上有一点延误，这样大家也能玩得很高兴啊

**Comment by NathanKun** [comment]
初始号问题不大倒是，花的钱是一次性。
能运行游戏+图像识别的服务器就很贵了，要24/7运行的话我肯定是付不起的，这方案不可持续。
我只能说我会尝试去做获取商品实时价格的功能吧，结果如何就不知道了。
