### ISSUE TITLE
仍然有部分商品排序不正确

### ISSUE THREAD

**Issue by Tsuk1ko** [NathanKun/resonance-columba#167]
发现还是有部分商品排序不正确的现象，例如七港

![image](https://github.com/NathanKun/resonance-columba/assets/24877906/51b517e6-3c36-4b7c-8d24-0e20e966bee0)

看起来商店内排序就是按原始售价从高到低排序

数据总表上面的排序也是不正确的，跟这个一样，看上去是 resonance-data-columba 里面的默认顺序，不过这个包您没放 github 上所以好像我也不能帮忙改😂

**Comment by NathanKun** [comment]
啊是的，我忘了数据总表里商品是先按类型排序再按价格排序了，所以特产斑节虾会排在前头。
现在改成按直接重新按基准价排序，应该好了。
感谢指正！

那个数据包是由一个闭源项目发布的。因为是基于那个解包项目，稳一手就不开源了。项目做了一系列的数据处理，可公开部分发布到resonance-data-columba。

（"你"就好了，别"您"😂

**Comment by Tsuk1ko** [comment]
（好的

看一图流已经正确了，不过我的意思其实是总表上的商品是否也应该直接按照游戏内排序，比较好对照

如果想让用户知道这个是特产的话感觉可以以别的方式，例如名字后面加★之类的🤔

**Comment by Tsuk1ko** [comment]
铁盟这里好像又不太对了，但是总表上的是正确的

![image](https://github.com/NathanKun/resonance-columba/assets/24877906/e82c24c9-2191-481b-ae06-494eb7c88d15)

![image](https://github.com/NathanKun/resonance-columba/assets/24877906/5fb7d7a8-2f62-4dc4-8b28-3ab1e67d2e95)

**Comment by NathanKun** [comment]
啊回城bug了，没仔细测。
这下应该修好了。
