### ISSUE TITLE
红绿与趋势无直接关系，产物可在产地卖出

### ISSUE THREAD

**Issue by Costantie** [NathanKun/resonance-columba#17]
颜色红绿和趋势无直接关系，事实上红色也能涨，建议拆分，
ps：虽然我没能理顺到底代表什么，但是似乎红绿只是简单的指示在原价之上还是之下，没有直接意义
产物可在产地直接卖出，建议增加

**Comment by tjulhx** [comment]
游戏里颜色和趋势是没关联的。
颜色代表当前商品是涨价还是掉价，红色代表低于基础价，绿色代表高于基础价，灰色就是基础价
趋势代表当前商品在下次更新价格时的价格趋势，向上代表要涨价，向下代表要掉价；但是不排除倒爷们大批量买入，大批量买入就不准了。

**Comment by NathanKun** [comment]
啊是的，游戏里红绿表示高于或低于基准价，和趋势没关系。我的表里红绿表示趋势，确实和游戏不同，一会儿改。

**Comment by NathanKun** [comment]
done in #18
