### ISSUE TITLE
api: https://www.resonance-columba.com/api/get-prices返回数据问题

### ISSUE THREAD

**Issue by exduke** [NathanKun/resonance-columba#173]
以下是2024/4/9/23:59的部分数据，可以看到没有"b"，其他大部分数据都有"b":{}
"10": {
            "s": {
                "1": {
                    "t": 1,
                    "v": 108,
                    "ti": 1712677384,
                    "p": 1823
                },
                "2": {
                    "t": 1,
                    "v": 113,
                    "ti": 1712676967,
                    "p": 2022
                },
                "3": {
                    "t": 1,
                    "v": 92,
                    "ti": 1712676136,
                    "p": 1801
                },
                "4": {
                    "t": 0,
                    "v": 104,
                    "ti": 1712676129,
                    "p": 1949
                },
                "5": {
                    "t": 0,
                    "v": 92,
                    "ti": 1712677394,
                    "p": 1801
                },
                "6": {
                    "t": 1,
                    "v": 94,
                    "ti": 1712677397,
                    "p": 1999
                },
                "7": {
                    "t": 0,
                    "v": 104,
                    "ti": 1712676965,
                    "p": 1949
                },
                "8": {
                    "t": 0,
                    "v": 103,
                    "ti": 1712676979,
                    "p": 1930
                },
                "9": {
                    "t": 0,
                    "v": 110,
                    "ti": 1712676141,
                    "p": 2154
                }
            }
        }

**Comment by NathanKun** [comment]
已在discussion回复。
所以接口返回的数据应该是对的吧？
