### ISSUE TITLE
您好，请问数据同步的api，我可以在其他项目里调用吗

### ISSUE THREAD

**Issue by Night-stars-1** [NathanKun/resonance-columba#187]
您好，请问数据同步的api，我可以在其他项目里调用吗
以降低玩家的数据迁移成本
![image](https://github.com/NathanKun/resonance-columba/assets/99261160/30488ec1-440d-4ea2-854e-eade394c2df4)

**Comment by NathanKun** [comment]
您好，很抱歉不可以，商会网站用的存储服务是按读写次数收费的，因此这个功能我没法给其他项目使用。
