### ISSUE TITLE
发射中心的蜂窝防热烧蚀材料数量貌似有误

### ISSUE THREAD

**Issue by Tsuk1ko** [NathanKun/resonance-columba#207]
发射中心声望19，苔妮5振，游戏中数量为17，一图流中为15，其他材料的数量都正确

![QQ截图20240504110241](https://github.com/NathanKun/resonance-columba/assets/24877906/dd154156-d179-4793-866f-ad52fb2123f4)

![image](https://github.com/NathanKun/resonance-columba/assets/24877906/22b2178f-4c81-4fd4-bc5e-9df190fbdfdb)

另外，乘员共振设置里面打错字了（

![image](https://github.com/NathanKun/resonance-columba/assets/24877906/548b35f7-4105-4077-81d4-fc0e37073a0a)

**Comment by NathanKun** [comment]
啊应该就是因为错字
