### ISSUE TITLE
看起来海角城的蕾丝连衣裙因为未知原因有了价格数据

### ISSUE THREAD

**Issue by DaiMao204** [NathanKun/resonance-columba#244]
现在海角城路线会推荐购买蕾丝连衣裙。但是这个还没解锁才对，看了眼数据，20多小时前获取到了一次100%出售的数据。

**Comment by NathanKun** [comment]
嗯有人手动提交了价格，可能是手滑了吧。我删掉了。
网站是允许玩家手动提交商品的价格信息的，这是最开始的功能，后来自动化价格获取后还是将这个功能保留了，作为自动化失效后的备用手段。
