### ISSUE TITLE
关于 部分制造物产地错误

### ISSUE THREAD

**Issue by DaiMao204** [NathanKun/resonance-columba#255]
年货大礼包、银制列车工艺品和金制列车工艺品的实际产地有误
虽然在当前情况下没有造成使用上的影响
但是是否应该矫正一下该错误 防止未来可能出现的问题？
年货大礼包-修格里城
银/金制列车工艺品-澄明数据中心

该错误没有实际的影响所以不用着急修复 可以等下次数据包更新的时候一并进行

**Comment by NathanKun** [comment]
我脚本里用的是配方里最后一个可购买的商品来定义这个制造品的产地。
比方说年货里的虾要在7号买所以归属到了7号。
因为游戏数据里除去一个中文描述外，我没找到明确将制造品归属到一个城市的参数。
我有空改改，比方说将制造品基础售价最低的城市作为归属城市之类的。

**Comment by DaiMao204** [comment]
制造物是有一个实际的归属城市的，虽然现在没有实际的参数。
在HomeGoodsFactory的对应制造物的idCN里能看到那个城市的名称，同时基础售价的最低城市也是那个。

**Comment by NathanKun** [comment]
Done in #261
