### ISSUE TITLE
搭建請益

### ISSUE THREAD

**Issue by Vincent-2019** [NathanKun/resonance-columba#272]
您好:
我是在臺灣地區的雷索納斯玩家
想跟您一樣架設相同的工具
但資料來源是從國際服的資料
想跟您請教如何架設
如果您願意傾囊相授這是我的wx

非常感謝!

**Comment by NathanKun** [comment]
你好，
商品的实时价格数据是通过真实的游戏账号在各个城市“挂机”的方式来获取的。
所以技术上需要能通过调用服务器的登录API才能进一步获取商品价格数据。
之前也有台湾的玩家在discussion上请求支持台服，当时我研究了一下台服的登陆机制，其中邮箱+验证码的登陆方式应该是较为简便的，但我没能破解登录请求的签名算法（没研究出来sig参数是怎么计算的）。
如果你想给台服假设同样的工具可能需要先解决登录问题，能解决的话我这边甚至可以单独出一个台服版本。
（我暂未提交wx好友请求）

**Comment by Vincent-2019** [comment]
您好，
我想要更深入了解您所敘述的登錄請求簽名算法，在我的思路中，是透過收發電子郵件的驗證碼(一個站點一個代碼一個帳號)的方式來登入，並透過圖像識別來抓取數字，因本身有參與過明日方舟的輔助腳本專案，本身我只擅長使用OCR，在麻煩您多做解釋，謝謝您

**Comment by NathanKun** [comment]
我抓包了一下邮箱登陆部分，共有两个请求。
第一个是给邮箱发验证码的请求，这部分没什么问题，我能成功调用并收到邮件，从邮件提取验证码也没什么难度。
关键是第二个请求，body里除去邮箱、验证码、和一堆杂七杂八的参数外，还有一个sig参数，是一个对当前请求的签名。比方说可以是将所有参数拼接成字符串然后加salt后做个hash之类的。根据我的测试，台独登录的服务端应该是会对收到的请求跑一遍同样的签名算法，检查收到的sig和服务端算出来的sig是否一致，只有一致时才会处理请求，否则直接返回错误。
我当时没试出来它的sig是怎么算的，就放弃了。
如果你有能力的话可以尝试反编译它unity库，找找登录部分的逻辑。

**Comment by Vincent-2019** [comment]
理解您的意思了，因為我是沒有能力去抓HASH算法的，但我有個想法，既然您都可以成功抓取到驗證碼，不如我加入個插件讓他自動輸入到驗證碼格子，您看是否可行
謝謝!

**Comment by NathanKun** [comment]
我是纯调用web api来登录与获取数据的，并没有实际运行游戏，只是发发http请求而已。能运行游戏的服务器太贵了，个人电脑不可靠，不是长久之计。

**Comment by Vincent-2019** [comment]
您好
我在經過這幾天的處理
可以將交易所物件轉化為CSV檔案(每1分鐘更新一次)
想跟您請教如何幫台獨們架設網站嗎?
謝謝!

**Comment by NathanKun** [comment]
台什么？？

**Comment by Vincent-2019** [comment]
台独

**Comment by NathanKun** [comment]
怎么就扯到政治了？

**Comment by Vincent-2019** [comment]
这不是重点啊哥们，我看着您上面也这么称呼的

**Comment by weinibuliu** [comment]
> 我抓包了一下邮箱登陆部分，共有两个请求。 第一个是给邮箱发验证码的请求，这部分没什么问题，我能成功调用并收到邮件，从邮件提取验证码也没什么难度。 关键是第二个请求，body里除去邮箱、验证码、和一堆杂七杂八的参数外，还有一个sig参数，是一个对当前请求的签名。比方说可以是将所有参数拼接成字符串然后加salt后做个hash之类的。根据我的测试，台独登录的服务端应该是会对收到的请求跑一遍同样的签名算法，检查收到的sig和服务端算出来的sig是否一致，只有一致时才会处理请求，否则直接返回错误。 我当时没试出来它的sig是怎么算的，就放弃了。 如果你有能力的话可以尝试反编译它unity库，找找登录部分的逻辑。

可能是你这条回复不小心打错字了？

**Comment by NathanKun** [comment]
你是指你能够获取台服实时商品价格信息，并能以csv或json方式提供是吗？
那我能想到最简单的方式就是clone这个项目，修改api/get-price，让它请求你的csv或json就好了，set-price 相关的功能可以删除。项目可以跟我一样通过vercel部署。

**Comment by Vincent-2019** [comment]
哈哈不好意思 误会了误会了
是的，我可以提供文档资料，但需要跟您请教您项目的使用办法和您所说
api/get-price的部分，谢谢您

**Comment by NathanKun** [comment]
这个如果你会前端/js/ts的话应该不难，根据readme应该就能把项目运行起来了，而且大部分代码都是有注释的。完全不会前端的话…三言两语我也说不清楚。
另外我比较好奇你的商品价格实时获取是怎么实现的，能简单说说吗？

**Comment by Vincent-2019** [comment]
哈哈理解了，能跟您请教一些可以着手研究的点吗，没有很深入学习过这些东西，但我还是试试看吧！
获取价格的部分我是用最硬核的方法，透过MaaFW来OCR识别价格并写入csv file，让同时让系统有容错能力（大概是遇到登入或是卡住的时候有相对应的解决方案）
我目前有两个想法：
1.透过Add-in插件同步本地和网页上的excel，并进行运算出价差最大的路线（类似黑子不黑大佬的Excel表格）
2.更改您的项目（获取价格的地方），并搭建一样的科伦巴台服网站
目前的困难就是我的能力还没办法去更改获取价格的地方（包含如何传送报文给Vercel服务器，且还要更改网站的繁体化和UI改动，这些都是尚未找到解决方法的。
但您放心，如果项目有成的话一定会在首页的标题感谢您的团队的帮忙的！

**Comment by NathanKun** [comment]
csv数据是在你本地的话，那首先要想一个将数据同步到远端服务器的办法。无论是excel还是网站，你的数据传出去后才能被调用。
excel方案我不太了解，如果能持续动态地导入你的csv的话那就没啥问题，路线计算方面慢慢完善就好。
网站的话需要不少web方面的知识，完全不懂的话恐怕没法轻易部署一个台服版本的商会。会web开发的话正如我前面所说，最主要的就是修改 api/get-prices 这个文件，让它访问你的csv文件就好。繁体化和UI改动都不会太难。
