### ISSUE TITLE
浙江电信已经完全没法直接访问了...能不能换个国内的服务器或者换个ip?

### ISSUE THREAD

**Issue by shty0008** [NathanKun/resonance-columba#274]
用站长工具也测了被墙了,测全国电信移动联通也基本上连不上了,
应该大多数人都连不上了
搜了下发现你用的是美国亚马逊的服务器. 那大概确实是被墙了.
![2 (1)](https://github.com/user-attachments/assets/b8f778da-ab22-4e3e-bd08-c4633ec5f6fa)
![2 (2)](https://github.com/user-attachments/assets/960600ea-4ef4-4a4a-afcd-c0b8d9c37fb2)

**Comment by NathanKun** [comment]
我这边vsping测速没问题。
不过还是尝试性地换了个cname，你再试试吧。

**Comment by shty0008** [comment]
哦 好了好了 感谢
