### ISSUE TITLE
乘员共振相关

### ISSUE THREAD

**Issue by DaiMao204** [NathanKun/resonance-columba#282]
能否将新增的未实装乘员共振相关内容暂时下掉呢。
这个新乘员涉及到联动相关的版权问题，官方未公布和实装之前最好还是先别外放

**Comment by NathanKun** [comment]
嗯现在应该去掉了。
数据是自动更新的，包里有了就自动放出来了。
有哪个属性能判断一个角色是否实装了吗？我有空改改。

**Comment by DaiMao204** [comment]
没有属性可以判断
但是可以用另一种方法
取到角色id之后 和BookFactory里的角色图鉴列表中比较一下 不在就不是
但是有时候他们更新可能会漏更图鉴 你可以参考一下这个办法
