### ISSUE TITLE
手机版网页最底下两栏的内容都无法查看，麻烦修复一下

### ISSUE THREAD

**Issue by shty0008** [NathanKun/resonance-columba#30]
还有希望能把手机版顶栏固定一下，现在往下拉后顶栏没固定
![Screenshot_2024-03-08-09-10-46-394_com mmbox browser](https://github.com/NathanKun/resonance-columba/assets/47084931/4d0c873e-ba70-4141-8cb0-01721adb328b)

**Comment by NathanKun** [comment]
fixed in #37
