### ISSUE TITLE
分别显示议价与不议价的利润

### ISSUE THREAD

**Issue by SilyASilyF** [NathanKun/resonance-columba#36]
NGA的老哥和我反映的，我确认过了。
不确定是不是prices-table.tsx里取值部分出了问题，目前计算单利得到的结果，与Products.ts中的价格乘以价位后，得到的差价是不同的。

example:
图中买入价为3840x1.07=4,108.8(他大概议价了一次降到了3835)，卖出价为4762xx0.89=4238，实际只有130的单利，与逻辑计算结果有非常大的差异，其他row似乎也如此。
![image](https://github.com/NathanKun/resonance-columba/assets/18006559/e74c9a7a-0f26-4d1f-8581-4ed7229557e8)
![image](https://github.com/NathanKun/resonance-columba/assets/18006559/ffd5c961-c0a2-4a7b-9c4f-09098f179988)

**Comment by NathanKun** [comment]
利润的计算我参考了原来的excel表。
成本 x 0.92
售价 x 1.04
这两个值我猜测是模拟议价。

你能否加上这两点再算一次？
谢谢

**Comment by SilyASilyF** [comment]
原来如此，这样的话我觉得不如直接展示原始价差和双满议价利润？
相对来说更直观一些。

只跑单趟不打算议价的人可能对原始价差比较敏感，货厢拉满的通常是长途满议价来获取最大利润，这样可以同时满足两种需求。

**Comment by NathanKun** [comment]
计算的实现不难，但这样每个城市又要增加两列，表格又更大了。
我得想想怎么合理的展示这些信息。
欢迎建议。

**Comment by SilyASilyF** [comment]
我的设想是不用加新的列，直接取代现有的单个利润和单批利润这两列。
目标是瞄准整个一单利润的人（即直接交易满仓且议价的人）不太会在乎单个商品的售价。
而在乎商品单价的人（只是顺路随便买一点，看看有没有赚头，并不打算议价的人）也能很快舍弃掉该站点单个利润很低，甚至在不议价的情况下反而亏损的那些商品。


当然还有一种方案，可能可以做成鼠标指针悬浮时显示不议价利润，否则默认显示满议价利润也不错。（渐变显示或悬浮窗显示？不确定是否容易实现）



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Junyang ***@***.***&gt;
发送时间: 2024年3月8日 19:23
收件人: NathanKun/resonance-columba ***@***.***&gt;
抄送: SilyASilyF ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [NathanKun/resonance-columba] [CRITICAL] 目前计算单利部分的逻辑好像出了问题 (Issue #36)





 
计算的实现不难，但这样每个城市又要增加两列，表格又更大了。
 我得想想怎么合理的展示这些信息。
 欢迎建议。

**Comment by NathanKun** [comment]
done in #45
