### ISSUE TITLE
脚本抓包能直接抓到所有数据

### ISSUE THREAD

**Issue by puresox** [NathanKun/resonance-columba#4]
如题，脚本抓包能抓到当前城市所有物品买卖数据，不需要别人上传

**Comment by puresox** [comment]
通过中间人拦截代理进行抓包（为了绕过http请求里的加密验证参数）能获取当前站点卖的所有商品的价格数据和全游戏所有商品卖到该站点的价格数据（不需要你包里有这些商品），所以通过将9个小号放在9个站点，就能抓到游戏里所有的商品价格数据了。思路我告诉老黑了，你可以找老黑合作。

**Comment by NathanKun** [comment]
这主要需要有服务器去持续抓包。需要多账号多开或轮流登录来抓不同城市的数据，或者需要用图像识别实现自动跑图，都不好做啊，而且能运行游戏的服务器都很贵。我暂时没想到什么好的实现和部署方法。

**Comment by puresox** [comment]
安卓模拟器轮流登录最简单，可以用家里的老电脑（狗头），不然没啥法子了
