### ISSUE TITLE
关于记忆设置的建议

### ISSUE THREAD

**Issue by Tsuk1ko** [NathanKun/resonance-columba#50]
希望可以永久记忆新版数据开关、原产地、目标城市这些设置

目前看网站貌似将设置储存在 cookie 里了，而且有效期为 session，即关闭浏览器再重新打开就没了，就得重新选，不是很方便

而且 cookie 每次请求都会通过 header 发一次有点浪费

是否可以储存在 localStorage 里，永久记忆

（而且即使是有意只想在 session 中保存，也可以使用 sessionStorage，比 cookie 好

（另外，新版数据的弹窗是否也可以加个“不再显示”

**Comment by NathanKun** [comment]
感谢建议。
用local storqge代替cookies done in #51
出于某种原因，新版数据开关暂时不打算记忆，弹窗也暂时不打算添加不再显示的功能。
