### ISSUE TITLE
网站的路线功能小bug

### ISSUE THREAD

**Issue by RudeusGreyrat666** [NathanKun/resonance-columba#57]
在城市声望填写19和20时会无法显示出路线

**Comment by RudeusGreyrat666** [comment]
是某个城填19或20声望，然后那个城作为原产地就会无法显示出路线

**Comment by NathanKun** [comment]
我目前只有8到18级声望的数据，请问你能否提供19和20级的数据？
我需要一般城市的税收百分比，7号自由港税收百分比，以及交易所买入量的加成。
比方说18级：城市的税收 5.5%，7号自由港税收 2.5%，以及交易所买入量的加成 80%

**Comment by NathanKun** [comment]
暂时先将声望等级上限设置为18了 #59

**Comment by RudeusGreyrat666** [comment]
我看下来声望等级界面里都是奇数等级加10%交易品可购买数量，偶数等级-0.5%税收。目前我就七号港20声望，是2%税收，图里的特产物品数量有朱利安共振4加20%
![七号港截图](https://github.com/NathanKun/resonance-columba/assets/148561865/1ae85b88-e17f-40b8-a771-d8e017466c4d)
![声望等级截图](https://github.com/NathanKun/resonance-columba/assets/148561865/02daf0d1-9394-440d-ac51-3af978dd19f4)

**Comment by RudeusGreyrat666** [comment]
![七号港声望加成](https://github.com/NathanKun/resonance-columba/assets/148561865/75dd7009-060d-454a-8714-4796033c5a50)

**Comment by NathanKun** [comment]
感谢。7号的数据有了，能否给个7号外的城市的截图？主要是确定税收，因为7号的税收和其他城市不同。

**Comment by RudeusGreyrat666** [comment]
修格里城只有18级
![修格里城18级声望税收](https://github.com/NathanKun/resonance-columba/assets/148561865/9c4b0696-243c-449b-a55a-e3bfd266fe7b)
![修格里城声望](https://github.com/NathanKun/resonance-columba/assets/148561865/088d4fc2-69f8-4a62-b49a-d62fe26cd8a6)

**Comment by NathanKun** [comment]
OK了，谢谢。
