### ISSUE TITLE
七号自由港的税率比其他城的低3%计算的时候是用的通用税率

### ISSUE THREAD

**Issue by arises** [NathanKun/resonance-columba#65]

**Comment by NathanKun** [comment]
能详细展开说说吗？你是算出来了网站模拟的七号自由港的税率错了吗？
我应该是有根据城市使用特殊税率或通用税率的。
```
        // apply prestiged tax to buy price
        const tax = buyPrestige.specialTax[fromCity] ?? buyPrestige.generalTax;
        buyPrice = Math.round(buyPrice * (1 + tax));
```

**Comment by arises** [comment]
比如研究所的 阿妮塔小型桦树发电机 基础价格6888 当前价位105% 我是13级自由港  硬核模拟中显示的价格是7739=6888*1.05*1.07 实际因该是6888*1.05*1.04

**Comment by NathanKun** [comment]
确实，研究所属于7号，应该使用7号的税率而不是通用税率。感谢指正。

**Comment by NathanKun** [comment]
https://github.com/all-contributors please add @arises for bug

**Comment by NathanKun** [comment]
@all-contributors please add @arises for bug
