### ISSUE TITLE
希望可以支持线路规划

### ISSUE THREAD

**Issue by st-hs** [NathanKun/resonance-columba#7]
我在构思一种基于实时价格表单的跑商路线规划系统，这完全可行，仅仅需要各个站点辗转的消耗值，物价表单，就能基于贪心或者动态规划来设计一个新的系统，我愿称之为雷索12306.
我正在使用您服务器的get-prices接口获取物价表单进行算法测试，如果可以 我们可以合作

**Comment by NathanKun** [comment]
路线规划当然是可行的，我有打算之后写这功能。也欢迎你提交PR。

**Comment by NathanKun** [comment]
会在#45中完成
