### ISSUE TITLE
角色共振加成计算问题

### ISSUE THREAD

**Issue by Tsuk1ko** [NathanKun/resonance-columba#88]
感谢作者加入这个功能，一直都很期待

但是试了下发现可能有计算问题，前提：矿场15级、甘雅振5特产+30%

首先我在一图流中实验无意中发现0票的进货仓位和游戏中不一致，于是去比较游戏中进货数量和硬核模拟中进货数量，发现特产数量对不上，其他商品对的上

![~0F28OM41M86P YA)16E %U](https://github.com/NathanKun/resonance-columba/assets/24877906/d8190594-a3a6-4db5-82be-fea5aa2224c9)

![HRU0X57V}`G (NNI9F1H5AY](https://github.com/NathanKun/resonance-columba/assets/24877906/a8a89528-2aeb-4de0-9b3c-0c21b325b744)

于是我试了下去掉甘雅的加成，发现计算出的仓位是30

![S0 _Q`A`{3D}{)$YLS1B%L](https://github.com/NathanKun/resonance-columba/assets/24877906/d0f2f3dd-e3fa-41c3-bbb4-65d44f577259)

因此我猜测，是否网站在计算的时候将角色共振加成最终乘算计算了，而实际在游戏中是与别的加成加算

**Comment by NathanKun** [comment]
感谢提醒。我对角色加成与声望加成进行了连续的乘算，这么看来应该是加成先相加再乘以基础数量。

**Comment by NathanKun** [comment]
修改后的计算结果与你提供的一致了。
![image](https://github.com/NathanKun/resonance-columba/assets/15254235/d1b5ebe2-54d9-4dc8-a2b3-fea589ab5d83)

**Comment by NathanKun** [comment]
@all-contributors please add @Tsuk1ko for bug
